#!/bin/bash

PIP=$(cat /etc/motd | grep "PUBLIC IP" | awk '{print $3}')
CIP=$(wget -qO- http://ipecho.net/plain)

if [ "$PIP" == "$CIP" ]; then

exit

else
   
echo "The Dynamic IP has changed to $CIP" | mutt -s "IP Change" kapoor.abhishek@outlook.com

fi

